DIRECTORY:
  dataset: 

TRAINER:
  model: effnet
  optimizer: adam
  learning_rate: 5.0e-4
  loss: crossentropy
  metric:
    - accuracy
    - f1macro
  n_epochs: 3
  early_stopping_target: val_accuracy
  early_stopping_patience: 10
  early_stopping_mode: max
  gpu: 0
  seed: 42

MODEL:
  Linear:
    n_inputs: 784
    n_outputs: 3
  effnet:
    n_outputs: 5

DATALOADER:
  batch_size: 16
  num_workers: 1
  shuffle: True
  pin_memory: True
  drop_last: False

LOGGER:
  logging_interval: 100
  plot:
    - loss
    - accuracy
    - f1macro
    - elapsed_time